server:
  port: 10081

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hoguking?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin!@#123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


---
spring:
  profiles: dev

---
spring:
  profiles: local

  datasource:
    url: jdbc:mysql://localhost:1306/hoguking?socket=/tmp/mysql.sock&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true


---
spring:
  profiles: real

  datasource:
    url: jdbc:mysql://e5f35db8-0cf0-409f-9ed4-7a43e741427e.private.rds.cloud.toast.com:11306/hoguking?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
